#!/bin/bash

declare -a cydia
cydia=($CYDIA)

if [[ $1 == upgrade || $1 == reinstall || $1 == remove ]]; then
	if [[ ${CYDIA+@} ]]; then
		eval "echo 'finish:restart' >&${cydia[0]}"
	fi
elif [[ $1 == install ]]; then
	if [[ ${CYDIA+@} ]]; then
		eval "echo 'finish:reboot' >&${cydia[0]}"
	fi
fi

exit 0